erdos-project/erdos

doc/requirements-doc.txt
doc/source/conf.py

- Fixes issue where autodoc for ROS integration required installation of `rospy`, `actionlib`, and `ray`
- Replaces `rospy`, `actionlib`, and `ray` with mock modules when generating documentation

Fix ROS integration documentation

---

erdos/data_stream.py
erdos/data_streams.py
erdos/graph.py
erdos/message.py
erdos/ray/ray_executor.py
erdos/ray/ray_input_data_stream.py
erdos/ray/ray_operator.py
erdos/ray/ray_output_data_stream.py
erdos/ros/ros_input_data_stream.py
tests/watermarks_test.py

- Added a new message type for `WatermarkMessage` that inherits from the base `Message`.
- Added a new `add_completion_callback` API to register callbacks for watermark messages.
- Changed the Ray init methods to match with the latest release.
- Tested using `watermarks_test` for both ROS and Ray.

Implementation of in-stream watermark messages for ROS/Ray

---

erdos/ray/ray_operator.py
erdos/ros/ros_input_data_stream.py

Fix Notes:
- The earlier implementation of watermarks would assume that every operator in the graph would add callbacks for watermarks and flow them forward, which might not always be the case. This fix propagates watermarks to downstream operators even if the operator does not implement callbacks for watermarks.
- Caveat: Double watermarks will flow if the operator does implement a callback and decides to propagate watermarks. This might need to be fixed in a future version of the code.
- Needs to re-cast a `Message` into a `WatermarkMessage` since Ray (as of 0.6.4) does not propagate types of variables correctly. (ref. ray-project/ray#4463)

[FIX] Propogate watermarks through the graph.

---

.gitignore
python/setup.py

Without this fix, wheels do not contain .py files.

Fix setup.py to include python files in wheel

---

experiments/throughput.rs
experiments/throughput_driver.rs
python/erdos/__init__.py
src/communication/endpoints.rs
src/communication/mod.rs
src/communication/pusher.rs
src/communication/receivers.rs
src/communication/senders.rs
src/configuration.rs
src/dataflow/graph/mod.rs
src/lib.rs
src/node/node.rs
src/python/mod.rs
src/scheduler/channel_manager.rs
tests/inter_thread_test.rs
tests/loop_test.rs
tests/utils.rs
tests/watermark_test.rs

Fixes the race condition where operators may begin executing before all nodes are connected and all operators are ready to run.
The following protocol on the control plane fixes the race condition:
1. The node executor spawns a green thread for each operator.
2.  Each operator initializes by calling `Operator::new()` and sends the `OperatorInitialized` message to the node executor.
3. The node executor waits until it has received `OperatorInitialized` messages from all operators. It then broadcasts the `AllOperatorsInitializedOnNode` message to all other nodes.
4. The node waits until it has received `AllOperatorsInitializedOnNode` messages from all nodes. It then begins executing operators via `Operator::run()`.
In addition to the protocol and control plane, this PR
- Refactors macros …

Fix race condition during setup

---

Cargo.toml
python/erdos/__init__.py
src/communication/control_message_codec.rs
src/communication/control_message_handler.rs
src/communication/endpoints.rs
src/communication/errors.rs
src/communication/message_codec.rs
src/communication/mod.rs
src/communication/receivers.rs
src/communication/senders.rs
src/communication/serializable.rs
src/dataflow/message.rs
src/node/node.rs
src/node/operator_executor.rs
src/python/mod.rs
src/scheduler/channel_manager.rs
tests/inter_thread_test.rs

This PR expands the control plane via the `ControlMessageHandler` by adding channels to and from `ControlSenders`, `ControlReceivers` `DataSenders` and `DataReceivers`.
The PR uses these changes to block on sender/receiver setup before running the driver and operators. Doing this fixes #61, as well as the un-reported "could not clone channel to node" issue.
Also fixes Python bugs that appeared when running `erdos.run_async`. This bug previously affected Python ingest and extract streams.
Finally, upgrades several libraries (notably tokio and futures) to the latest stable versions.

Expand control plane to senders and receivers and update libraries

---

Cargo.toml
python/erdos/__init__.py
src/communication/control_message_handler.rs
src/communication/mod.rs
src/node/node.rs

The race condition occurs on multi-node (3+) setups when one node initializes slightly faster than the others. Messages were assumed to arrive in a specific order; however, messages were reordered if a node initialized before the others which led to messages mistakenly being dropped.
Closes #63

Fix race condition in system initialization

---

scripts/make_callback_builder.py
src/dataflow/message.rs

This PR fixes a bug in the low watermark computation. Previously, the watermark callback would not be invoked in the following situations:
1. Operator receives on stream 1 a watermark for timestamp t.
2. Operator receives on stream 2 a watermark for timestamp t + 1.
This PR ensures that we first compute the previous low watermark across all streams, update the low watermark on the stream we've received a watermark, and computes the new low watermark across all streams. The watermark callback is invoked if the new low watermark is higher that the previous low watermark.

Bug fix in the low watermark computation.

---

src/lib.rs

I couldn't find a better way to do this type checking at compile time -- the closest I got was [`std::compile_error`](https://doc.rust-lang.org/std/macro.compile_error.html), but I couldn't find a way to interface this with the type checking.

Verify that corresponding types in `new()` and `connect()` match

---

Cargo.toml
experiments/throughput_driver.rs
src/communication/endpoints.rs
src/communication/errors.rs
src/communication/pusher.rs
src/communication/receivers.rs
src/dataflow/graph/mod.rs
src/dataflow/mod.rs
src/dataflow/stream/ingest_stream.rs
src/dataflow/stream/internal_read_stream.rs
src/dataflow/stream/mod.rs
src/dataflow/stream/write_stream.rs
src/lib.rs
src/node/node.rs
src/node/operator_event.rs
src/node/operator_executor.rs
src/python/mod.rs
src/scheduler/channel_manager.rs
src/scheduler/endpoints_manager.rs
tests/inter_thread_test.rs

- Avoids busy looping for invoking callbacks by moving streams and operator executor to tokio.
- Replaces std channels with tokio channels to prevent blocking of OS threads (which may cause starvation/block the entire runtime).
- Calls to `ReadStream::read` now busy loop, but don't interfere with the runtime. To solve this issue, we may want to move operators to tokio in the future, make `run` async, and implement an async `ReadStream::read`.
- Fixes a bug in the single node case where `Node::run_async` may finish running while operators should still be running.
Performance of `python/examples/watermarks.py` before fixes (note 3 CPUs at 100%):
Performance of `python/examples/watermarks.py` before fixes (note 1 CPU at 100% due to `PullWatermarkListener`):

Move streams and operator executor to Tokio

---

doc/source/index.rst
python/erdos/__init__.py
python/examples/ingest_extract.py
python/examples/join_streams.py
python/examples/loop.py
python/examples/simple_pipeline.py
python/examples/watermarks.py

API-breaking PR which removes the need to pass a driver function to `erdos.run()` and `erdos.run_async()`.
This PR simplifies the python API and removes a bug in which python nodes had superfluous copies of the dataflow graph.

Remove python driver function

---

tests/utils.rs

Fixes #61. This PR assigns unique ports to each node used in a test.
Previously, `cargo test` would run tests in parallel in separate threads. Nodes requested the same ports which occasionally resulted in deadlock if one test acquired the control port and another acquired the data port.
Thanks to shepmaster whose [solution in this thread](https://users.rust-lang.org/t/unique-id-per-test/33882/4) was adapted into the fix.

Fix hanging tests

---

src/node/node.rs
tests/inter_thread_test.rs

`Node::run_async` returns a `NodeHandle` which exposes `join` and `shutdown` methods. `join` blocks until the node finishes. `shutdown` sends a shutdown message to the node, and then blocks until shutdown is complete.

Implement shutdown for nodes

---

src/dataflow/mod.rs
src/dataflow/stream/internal_read_stream.rs
src/dataflow/stream/mod.rs
src/dataflow/stream/read_stream.rs
src/lib.rs

Removes the `ReadStreamT` trait since it is unused/unnecessary in its current state.

Remove ReadStreamT trait

---

experiments/throughput_driver.rs
src/dataflow/mod.rs
src/dataflow/operator.rs
src/dataflow/operators/join_operator.rs
src/dataflow/operators/map_operator.rs
src/dataflow/operators/source_operator.rs
src/lib.rs
tests/inter_thread_test.rs
tests/loop_test.rs
tests/watermark_test.rs

- Renames `OperatorT` trait to `Operator`.
- Removes `get_name` and `get_id` methods from `Operator` trait.
- Add compile-time check that operators implement `Operator`.

Operators must implement Operator trait

---

python/erdos/__init__.py
python/erdos/operator.py
python/examples/simple_pipeline.py
src/python/mod.rs

Adds name and ID properties to python operators. These can be accessed as `self.name` and `self.id`.
In addition, moves setup for `_trace_events` to the `__new__` function. This avoids forcing users to call the `erdos.Operator.__init__()`. We might change this in the future.
Note that the `uuid` package is available in python 3.5+.

[Python] Add name and ID properties to erdos.Operator

---

doc/source/index.rst
doc/source/operators.rst
python/erdos/__init__.py
python/erdos/operator.py
python/erdos/utils.py
python/examples/ingest_extract.py
python/examples/join_streams.py
python/examples/loop.py
python/examples/simple_pipeline.py
python/examples/watermarks.py
src/python/mod.rs

Adds an `OperatorConfig` class which must be passed into `erdos.connect`, matching the Rust API.
Also adds the `config` property to the `Operator` base class.

[Python] Add OperatorConfig

---

src/lib.rs
tests/macro_tests.rs

This commit fixes connect_2_write and connect_3_write macros.
Introduces tests to ensure connect_2_write! and connect_3_write! are tested.
Refactors connect macros to reduce the number of branches.

Fixing connect macros.

---

python/erdos/__init__.py
python/examples/close_streams.py
src/node/node.rs
src/python/mod.rs

`run_async` now returns a `NodeHandle` which implements the `shutdown` method for the dataflow.
For example:
```python
node_handle = erdos.run_async()
node_handle.shutdown()
```
Other changes:
- updated the close stream example to shut down.
- fixed a bug that caused errors when `config.name` is `None`

[Python] Enable shutting down dataflows

---

Cargo.toml

Minor fix which improves build time by making pyo3 an optional dependency. This improves build time when building the core system.
This PR doesn't change the build process; pyo3 is automatically included when building for python.

Make pyo3 an optional dependency

---

Cargo.toml
src/node/lattice.rs
src/node/mod.rs
src/node/operator_event.rs
src/node/operator_executor.rs

- Adds a dependency to `petgraph` which provides the underlying directed acyclic graph implementation.
- Implements the `PartialOrd` trait for the OperatorEvent to partially order events based on their timestamps and watermark status.
- Implements the `ExecutionLattice` class that partially orders the incoming events and provides an API to retrieve the events that are safe to run.

Implement ExecutionLattice to partially order incoming events.

---

src/lib.rs
src/node/node.rs
src/node/operator_executor.rs
src/python/mod.rs
tests/inter_thread_test.rs
tests/loop_test.rs
tests/watermark_test.rs

OperatorExecutors now call `Operator::run` from an async context. This allows waiting on the `RunOperator` signal using a blocking call instead of busy-looping.
Also fixes some bugs in the tests.
Fixes #102.

Call Operator::run from OperatorExecutor to remove busy-looping

---

scripts/make_callback_builder.py
src/dataflow/message.rs
src/dataflow/mod.rs
src/dataflow/state.rs
src/dataflow/stream/internal_stateful_read_stream.rs
tests/state_tests.rs

Adds time-versioned state which ensures that an operator behaves deterministically while allowing as much parallelism as possible.
Time-versioned state enforces 3 different access patterns:
1. When created in Operator::new(). This allows setting the number of past states accessible via the history size and an initial state associated with `Timestamp::bottom()`.
2. From a regular, non-watermark callback. This allows appending messages which are later exposed to watermark callbacks. Appended messages may be compressed versions of ERDOS messages.
3. From a watermark callback. This allows reading appended messages and reading state up until current timestamp. In addition, it allows mutating the state associated with the current timestamp.
For each access pattern, access rules are enforced via …

Add time-versioned state to enforce determinism

---

src/lib.rs

Re-exports crates used in ERDOS macros so that crates using ERDOS don't need to explicitly import them.
Before, crates using ERDOS would need to add dependencies for slog and tokio in `Cargo.toml`.
This is no longer necessary now.

Fix macro imports for external crates

---

src/dataflow/operator.rs
src/node/operator_executor.rs

Adds the `num_event_runners` setting to `OperatorConfig` which sets the maximum number of callbacks an operator can process in parallel.
This PR is a step towards implementing multi-threaded operators.

Enable processing callbacks in parallel

---

python/erdos/__init__.py

Fixes a bug where ERDOS would launch too many python processes after resetting the dataflow.

[Python] Fix bug in erdos.reset()

---

src/lib.rs
src/node/lattice.rs

- This change uses a BinaryHeap instead of a Vec to order events that are ready to run. (hopefully prevent starvation)
- Adds a new test to ensure that the behavior is as expected.

Use a BinaryHeap to order events.

---

Cargo.toml
benches/latency.rs
scripts/make_callback_builder.py
src/communication/endpoints.rs
src/communication/errors.rs
src/communication/message_codec.rs
src/communication/mod.rs
src/communication/pusher.rs
src/communication/receivers.rs
src/communication/senders.rs
src/communication/serializable.rs
src/dataflow/message.rs
src/dataflow/mod.rs
src/dataflow/operators/join_operator.rs
src/dataflow/operators/map_operator.rs
src/dataflow/stream/internal_read_stream.rs
src/dataflow/stream/internal_stateful_read_stream.rs
src/dataflow/stream/mod.rs
src/dataflow/stream/read_stream.rs
src/dataflow/stream/stateful_read_stream.rs
src/dataflow/stream/write_stream.rs
src/lib.rs
src/node/operator_executor.rs
src/scheduler/channel_manager.rs
src/scheduler/endpoints_manager.rs
tests/inter_thread_test.rs
tests/operator_test.rs
tests/state_tests.rs
tests/watermark_test.rs

- Adds zero-copy communication for operators colocated on the same node.
- Zero-copy mechanisms speed up cross-node communication by reducing copies on the communication path.
- Further speed up cross-node communication by serializing directly into the network buffer.
- Operators receive references to timestamps and messages rather than taking ownership to further reduce copies.

Implement zero-copy communication

---

src/communication/control_message_handler.rs
src/communication/mod.rs
src/communication/receivers.rs
src/communication/senders.rs
src/dataflow/graph/mod.rs
src/dataflow/message.rs
src/dataflow/mod.rs
src/dataflow/operators/mod.rs
src/dataflow/stream/ingest_stream.rs
src/dataflow/stream/mod.rs
src/dataflow/stream/write_stream.rs
src/lib.rs
src/node/lattice.rs
src/node/mod.rs
src/node/node.rs
src/python/mod.rs
src/python/py_stream/mod.rs
src/scheduler/mod.rs

Reorganizes `mod.rs` files so they follow the following format:
```rust
// Library imports (e.g. from std)
// Private submodules
// Crate-wide visible submodules
// Public submodules
// Private imports
// Crate-wide exports
// Public exports
// Functions, struct declarations, implementation, etc.
```
Also restricts visibility of submodules and other objects to reduce the amount of internal objects visible in the public documentation.

Reorganize modules to restrict visibility

---

src/dataflow/operators/map_operator.rs
src/lib.rs
src/main.rs
src/node/lattice.rs
src/python/mod.rs
src/python/py_stream/py_ingest_stream.rs
tests/inter_thread_test.rs
tests/macro_tests.rs
tests/operator_test.rs
tests/state_tests.rs

Fixes warnings when building ERDOS, tests, or the documentation.
Also fixes a minor bug introduced in the python bridge.
Makes variable naming in the tests more consistent.

Fix warnings

---

Cargo.toml
src/communication/serializable.rs
src/lib.rs
src/node/lattice.rs

- The Rust specialization feature rust-lang/rust#31844 is unsound and throws a warning on the latest nightly. This PR moves to min_specialization which fixes the warning.
- [Forks abomonation](https://github.com/erdos-project/abomonation) in order to allow specialization on structs that implement `Abomonation`.
- Replaces use of `Vec::remove_item` to end reliance on the deprecated `vec_remove_item` feature.

[Rust] Fix new nightly errors

---

README.md
build.rs
scripts/make_callback_builder.py
src/lib.rs

Replaces fire with argparse in the Python script that generates the callback builders.
This change removes a step from the install process.

Replace fire with argparse

---

scripts/make_callback_builder.py
src/connect.rs
src/dataflow/stream/internal_read_stream.rs
src/dataflow/stream/internal_stateful_read_stream.rs
src/node/lattice.rs
src/node/operator_event.rs
src/node/operator_executor.rs

Can add priorities to callbacks which are exposed via a bundle's `add_watermark_callback_with_priority` method.
Some details:
- Smaller numbers imply higher priority.
- Priority currently only affects the ordering and concurrency of watermark callbacks.
- For two otherwise equal watermark callbacks, the lattice creates a dependency from the lower priority event to the higher priority event. Thus, these events cannot run concurrently, with the high-priority event running first. An effect is that only watermark callbacks with the same priority can run concurrently.
Unfortunately, this doesn't solve the flow watermarks bug by itself due to the way operator events are created, which I'll take a look at next.

Add Priorities for OperatorEvents

---

src/node/lattice.rs
src/node/operator_event.rs

- Changes operator event ordering s.t. `x < y` implies `x` *precedes* `y`.
- Reverse edges on lattice dependency graph to match [convention](https://en.wikipedia.org/wiki/Dependency_graph).
- Add warning if more than 25 events queued in lattice.
- Add `to_dot` method to lattice for easier visualization/debugging.
- Code refactoring and comments on lattice.
- Tests use `assert` instead of `assert_eq(*, true)`.

Refactor operator event ordering and lattice

---

src/dataflow/operator.rs
src/dataflow/operators/join_operator.rs
src/dataflow/operators/map_operator.rs
src/dataflow/stream/extract_stream.rs
src/dataflow/stream/ingest_stream.rs
tests/operator_test.rs
tests/watermark_test.rs

Also updates documentation for `JoinOperator` and `MapOperator` to fix builder pattern, rename streams, and hide lines unnecessary to the example in the documentation.

Simplify and document OperatorConfig builder pattern

---

.github/workflows/ci.yaml
.github/workflows/docs.yaml
.github/workflows/wheels.yaml
Cargo.toml
README.md
doc/source/conf.py
python/build-wheels.sh
python/setup.py

Enables nightly builds for Python wheels via GitHub actions. Builds start at 12am Pacific (7am UTC) and take around 30 minutes to finish. Also updated the script for building wheels.
This should be merged after #143.

Enable nightly builds for Python wheels

---

src/dataflow/graph/default_graph.rs
src/node/node.rs

Fixes the use of the global dataflow graph in `node.rs` to be compatible with other executors.
The global dataflow graph is a thread local variable. Because tokio's `runtime.block_on` donates the current thread to the asynchronous task when `Node::async_run` is called, this works out. However, this leads to a bug when using a runtime that spawns `Node::async_run` onto another thread where the global dataflow graph used by `async_run` is unpopulated.
The fix assigns the populated global dataflow graph to `node.dataflow_graph` which is then safely used across asynchronous functions.

Modify use of global dataflow graph for use with other executors

---

src/python/py_stream/py_extract_stream.rs

Fixes a bug in the implementation of `ExtractStream.try_read()` in the Python API.
https://github.com/erdos-project/erdos/blob/8b5715a9e1baf35108dd2cc259de5f652adf0da7/python/erdos/streams.py#L301-L309

Implement try_read for PyExtractStream

---

src/node/operator_executor.rs

Fixes a bug in operators with no input streams where `destroy()` would not be invoked after `run()` finishes.
Note: although `destroy()` will be invoked, top watermarks are *not* automatically sent on output streams.

[Bugfix] Destroy operator when run finishes

---

src/dataflow/operator.rs
src/node/operator_executor.rs

PR to track the deduplication of the `OperatorExecutor` code. Changes are as follows:
- Require the operator traits to be both `Send` and `Sync`.
- Introduce `MessageProcessorT` trait that must be implemented by each executor and provides a way to create new `OperatorEvent`s for stateless and stateful message callbacks along with watermark callbacks.
- Introduce `OperatorExecutorHelper` struct that performs the common tasks of synchronization of the operators, creation of channels, processing of messages and teardown. It invokes the abstractions provided by the `MessageProcessorT` trait to generate events for the lattice. 
Curent status:
- Moved `SourceOperator` and `SinkOperator` to the new abstractions.

Introduce MessageProcessorT and OperatorExecutorHelper abstractions.

---

src/dataflow/message.rs
src/dataflow/mod.rs
src/dataflow/state.rs
src/dataflow/stream/mod.rs
src/dataflow/stream/write_stream.rs
src/dataflow/time.rs
src/main.rs
src/node/lattice.rs
src/node/operator_event.rs
src/node/operator_executor.rs
tests/inter_thread_test.rs
tests/watermark_test.rs

- Changes the `IntTimestamp` structure to `enum` with `Top`, `Bottom` and `Time(vec<u64>)`.

Rewrite IntTimestamp to enum.

---

src/dataflow/deadlines.rs
src/dataflow/stream/read_stream.rs
src/dataflow/stream/write_stream.rs
src/node/operator_executor.rs

- Maintains message statistics in `ReadStream` and `WriteStream`.
- Executes start conditions on the statistics of the `ReadStream` and the end conditions on the statistics of the `WriteStream`.

Fix end condition execution and maintain message statistics in streams.

---

src/dataflow/graph/graph.rs
src/dataflow/stream/extract_stream.rs
src/dataflow/stream/ingest_stream.rs

Modifies IngestStreams and ExtractStreams to run on node 0, which is a first step towards providing a single driver for ERDOS programs.
As a temporary solution, the dataflow graph places ingest and extract streams on node 0. I'll improve this abstraction in a follow-up PR in which I'm planning to refactor the dataflow graph.

Run IngestStreams and ExtractStreams on Node 0

---

Cargo.toml
src/communication/control_message_handler.rs
src/communication/mod.rs
src/configuration.rs
src/dataflow/deadlines.rs
src/dataflow/operators/filter_operator.rs
src/dataflow/operators/map_operator.rs
src/dataflow/operators/split_operator.rs
src/dataflow/stream/extract_stream.rs
src/dataflow/stream/ingest_stream.rs
src/dataflow/stream/write_stream.rs
src/lib.rs
src/main.rs
src/node/lattice.rs
src/node/node.rs
src/node/operator_executors/mod.rs
src/node/operator_executors/source_executor.rs
src/node/worker.rs
src/python/mod.rs
src/python/py_operators/py_one_in_one_out.rs
src/python/py_operators/py_one_in_two_out.rs
src/python/py_operators/py_sink.rs
src/python/py_operators/py_source.rs
src/python/py_operators/py_two_in_one_out.rs
tests/inter_thread_test.rs

Switches logging to [tracing](https://github.com/tokio-rs/tracing) from [slog](https://github.com/slog-rs/slog).
- More customization for logging via the Node configuration and command line interfaces.
- Rename `num_worker_threads` to `num_threads` to distinguish from the worker tasks.
- Supports [spans](https://docs.rs/tracing/0.1.29/tracing/#spans) for monitoring the progress/duration code contexts. I've found this useful for concurrent debugging.
- Tracing integrates with Tokio and provides support for async contexts.
- Don't need to pass a logger when recording events.
- Support for additional logging interfaces (e.g. writing to file, integrating with [OpenTelemetry](https://github.com/tokio-rs/tracing/tree/master/tracing-opentelemetry)).
- Easy to add additional information such as …

Switch logging to tracing from slog

---

erdos/src/dataflow/operator.rs
erdos/src/dataflow/operators/ros/from_ros_operator.rs
erdos/src/node/operator_executors/one_in_one_out_executor.rs
erdos/src/node/operator_executors/one_in_two_out_executor.rs
erdos/src/node/operator_executors/sink_executor.rs
erdos/src/node/operator_executors/source_executor.rs
erdos/src/node/operator_executors/two_in_one_out_executor.rs
examples/erdos_to_ros.rs
examples/full_pipeline.rs
python/src/py_operators/py_one_in_one_out.rs
python/src/py_operators/py_one_in_two_out.rs
python/src/py_operators/py_sink.rs
python/src/py_operators/py_source.rs
python/src/py_operators/py_two_in_one_out.rs

* Adds a `config: &OperatorConfig` to all operators
* Updated examples and ros operators
* `config` is currently unused in the Python interface (Rust warnings)

Add OperatorConfig to operator run method

---

erdos/src/dataflow/operators/ros/from_ros_operator.rs
erdos/src/dataflow/operators/ros/to_ros_operator.rs
erdos/src/dataflow/stream/extract_stream.rs
erdos/src/dataflow/stream/ingest_stream.rs

- Mocks `rosrust_msg` library for the ROS doctests.
- Only compiles (and does not run) the tests for `IngestStream` and `ExtractStream` since they run a ROS node.

Fix doctests for ROS operators.

---

erdos/src/dataflow/operators/concat.rs
erdos/src/dataflow/operators/map.rs
erdos/src/dataflow/operators/mod.rs
erdos/src/dataflow/stream/extract_stream.rs
erdos/src/dataflow/stream/ingest_stream.rs
erdos/src/dataflow/stream/loop_stream.rs
examples/full_pipeline.rs
examples/linq.rs

- Replaces `MapOperator` with a more general `FlatMapOperator`.
- Updates documentation.
- Fixes examples and tests.

[LINQ] Replace MapOperator with FlatMapOperator, and add flat_map to API.

---

erdos/src/dataflow/connect.rs

Fixes a bug where `connect_two_in_one_out` would instantiate two copies of the same write stream during execution, rather than one for the left write stream and another for the right write stream.
Also does some code cleanup.

[Bug] Fix connect_two_in_one_out

---

.github/workflows/docs.yaml
erdos/src/dataflow/operators/ros/from_ros_operator.rs
erdos/src/dataflow/operators/ros/to_ros_operator.rs
erdos/src/dataflow/stream/extract_stream.rs
erdos/src/dataflow/stream/ingest_stream.rs
erdos/src/lib.rs

- The rustdoc check fails if building the documentation produces any warnings.
- Enables all features when building the documentation.
- Fixes errors in the documentation, add iterates on ROS operator documentation.
- Adds caching to the rustdoc workflow, reducing run times in CI from ~2.5 minutes to ~30 seconds.

[CI] Fail on warnings when building Rust docs

---

.github/workflows/ci.yaml
python/Cargo.toml
python/src/py_message.rs
python/src/py_timestamp.rs

- Bumps pyo3 to 0.16.0 and moves dunder methods from `pyproto` implementation to `pymethods` (documented [here](https://pyo3.rs/master/class/protocols.html)).
- Remove `clippy::unneeded_option_deref` from CI build arguments.

Bump PyO3 version and fix CI

---

erdos/src/dataflow/connect.rs
erdos/src/dataflow/context.rs
erdos/src/dataflow/operators/join.rs
erdos/src/dataflow/operators/mod.rs
erdos/src/dataflow/state.rs
examples/linq.rs

Introduces the `TimestampJoin`, which joins messages with matching timestamps from two different streams by performing a cartesian product. I've tested the operator locally, and it seems to work.
A few things I wasn't sure about that can hopefully be addressed in review:
1. Consistent naming: `TimestampJoin` seems more ergonomic, but this should be named `TimestampJoinOperator` to stay consistent with the other operators.
2. Example: I wasn't sure how to best add the timestamp join to the existing LINQ and full pipeline examples. These examples may also need to be revamped.

[LINQ] Add timestamp join

---

python/erdos/streams.py
python/examples/linq.py
python/examples/linq_api.py
python/src/py_stream/mod.rs

- Provides the `map`, `flat_map`, `filter`, `split`, `timestamp_join` and `concat` methods from Rust in Python.
- Enables developers to provide multiple streams to `concat` to ease the implementation of multi-in operators.
Potential TODOs:
- Syntactic sugar over the `split` method to enable developers to specify the type of outputs expected and automatically route them to different streams.
- Our Rust `timestamp_join` does not allow developers to specify a `join_function` similar to `apply` in Flink, which could prevent the addition of an extra `map` when doing `timestamp_join`s in Python.

[Python] Expose ERDOS' LINQ API in Python

---

erdos/src/scheduler/channel_manager.rs

Fixes a bug when setting up streams and operators. ERDOS would improperly set up channels within a stream, causing a crash if:
1. A stream originates on node A
2. 2 operators collocated on node B are connected to that stream.

[Bug] Enable cross-node streams to connect collocated operators

---

erdos/src/node/operator_executors/one_in_two_out_executor.rs

Fix an issue when `flow_watermarks=False` does not execute watermark callbacks.

[Bug] Fix deadlock in watermark callbacks

---

python/src/lib.rs

Fixes an error when importing ERDOS in python:
```
In [1]: import erdos                                                                                                                                                                                       
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-a99ca392442f> in <module>
----> 1 import erdos
~/workspace/erdos/python/erdos/__init__.py in <module>
369 # TODO (Sukrit) : Should this be called a GraphHandle?
370 # What is the significance of the "Node" here?
--> 371 class NodeHandle:
372     """A handle to the dataflow graph returned by the :py:func:`run_async`
373     function. …
```

[Bug] Fix import error for PyNodeHandle
