- Dockerfile
- README.md
- install_dependencies.sh
- Added a `docker pull erdos` command to README.
- Fixed the Dockerfile to now clone the public repository instead.
- Fixed `install_dependencies.sh`.
> Fixed Docker and installation scripts.

- erdos/data_stream.py
- erdos/data_streams.py
- erdos/graph.py
- erdos/op_handle.py
- erdos/ray/ray_input_data_stream.py
- erdos/ray/ray_operator.py
- erdos/ray/ray_output_data_stream.py
- erdos/ros/ros_input_data_stream.py
- erdos/ros/ros_output_data_stream.py
Addressed https://github.com/erdos-project/erdos/issues/7
> [Bug] Fix stream name clashing problem

- erdos/graph.py
- Add parent graph to constructor. This is necessary for checking valid connections when later using the `with` API.
- Add static `setup_streams`. From our discussion earlier today, we want to treat graphs as operators and maintain a similar API. Unfortunately, connecting streams to operators and getting streams from operators is difficult under the current API, so we cannot support `setup_streams` until we redesign streams.
- Add non-static `construct` method. This is _temporary_ solution to allow implementation of nested graphs until we redesign streams.
> Add new graph API

- python/erdos/__init__.py
- python/examples/ingest_extract.py
- python/examples/join_streams.py
- python/examples/loop.py
- python/examples/simple_pipeline.py
- python/examples/watermarks.py
Makes ERDOS python 3.5 compatible.
Also fixes some formatting.
> Fix Python 3.5 compatibility

- .gitignore
- python/README.md
- python/build-wheels.sh
- python/erdos/__init__.py
- python/examples/ingest_extract.py
- python/examples/join_streams.py
- python/examples/loop.py
- python/examples/simple_pipeline.py
- python/examples/watermarks.py
- Fixes the `build-wheels.sh` script which generates wheels.
- Adds a README to the python directory which describes how to generate wheels using [manylinux](https://github.com/pypa/manylinux).
> Fixes and documentation for building wheels

- python/erdos/__init__.py
Fixes `run_async` which was broken by #59
> [Python] Fix run_async

- src/lib.rs
Cosmetic change which reduces the number of indents in macros by 1.
> Decrease indents in macros

- Cargo.toml
- src/dataflow/message.rs
- src/dataflow/operators/join_operator.rs
- src/dataflow/operators/map_operator.rs
- src/main.rs
- tests/operator_test.rs
- tests/watermark_test.rs
- This PR provides the implementation of MapOperator and JoinOperator along with the relevant tests.
> MapOperator and JoinOperator Implementation.

- python/erdos/__init__.py
- src/python/mod.rs
Removes obsolete python implementation for flowing watermarks.
> [Python] Remove duplicate flow watermarks implementation

- python/erdos/__init__.py
- src/python/mod.rs
Reverts erdos-project/erdos#116
> Revert "[Python] Remove duplicate flow watermarks implementation"

- .github/workflows/docs.yaml
- doc/source/index.rst
- doc/source/intro.rst
- doc/source/messages.rst
- doc/source/operators.rst
- doc/source/package_reference.rst
- doc/source/streams.rst
- python/erdos/operator.py
- src/lib.rs
Updates Python documentation and adds building Python documentation to CI.
You can view the updated documentation [here](https://people.eecs.berkeley.edu/~pschafhalter/pub/erdos/pydoc/) (I might take this offline after the PR gets merged).
> [Python] Update documentation

- python/erdos/__init__.py
The join can be used to block until all process from a node complete.
> Added join method on a node handle.

- Cargo.toml
- src/communication/control_message_codec.rs
- src/communication/message_codec.rs
Updated dependencies so that we can benefit from the newer Tokio features (e.g., https://tokio.rs/blog/2020-04-preemption).
> Updated crate dependencies.

- Cargo.toml
- README.md
- doc/source/conf.py
- python/setup.py
> Release v0.3.1

- src/dataflow/connect.rs
- src/dataflow/deadlines.rs
- src/dataflow/mod.rs
- src/dataflow/operator.rs
- src/dataflow/state.rs
- src/dataflow/stream/loop_stream.rs
- src/main.rs
- src/node/operator_executor.rs
- Implemented `TimestampDeadline` for the `OneInOneOutOperator`.
- Initial definitions for `SetupContext` for the `setup` functions to be introduced in the operators, `HandlerContextT` for the handlers registered with the deadline and `ConditionContext` for the information available to the start and end conditions.
> Implement Timestamp Deadlines.

- python/erdos/__init__.py
- python/examples/simple_pipeline.py
Changes:
* Update `simple_pipeline.py` for erdos redesign
* Fix multiprocessing process issue on macOS for Python 3.8+
> Update simple pipeline example

- python/erdos/__init__.py
- python/erdos/streams.py
- src/python/py_operators/py_one_in_one_out.rs
- src/python/py_operators/py_one_in_two_out.rs
- src/python/py_operators/py_sink.rs
- src/python/py_operators/py_source.rs
- src/python/py_operators/py_two_in_one_out.rs
- src/python/py_stream/py_ingest_stream.rs
- src/python/py_stream/py_read_stream.rs
- src/python/py_stream/py_stream.rs
- src/python/py_stream/py_write_stream.rs
* Add name setters and getters to PyStream, PyIngestStream, PyReadStream, PyWriteStream
* Remove `_name` from Python constructors
* Add set_name to streams in Python
> [Python] Add name setters and getters

- src/node/operator_executors/one_in_one_out_executor.rs
- src/node/operator_executors/one_in_two_out_executor.rs
- src/node/operator_executors/sink_executor.rs
- src/node/operator_executors/two_in_one_out_executor.rs
Deadlocks could occur because functions generating operator events for messages and callbacks sometimes acquire locks in different orders.
The message callback in `OneInOneOutExceutor` acquires a lock on the operator before the state:
https://github.com/erdos-project/erdos/blob/54c2a4db7bbef272de8ad09e578a8188ddae0f3d/src/node/operator_executors/one_in_one_out_executor.rs#L344-L354
Whereas the watermark callback acquires a lock on the state before the operator:
https://github.com/erdos-project/erdos/blob/54c2a4db7bbef272de8ad09e578a8188ddae0f3d/src/node/operator_executors/one_in_one_out_executor.rs#L406-L421
> [Bug] Fix possible deadlock in operator executors

- src/python/mod.rs
Fixes issues introduced by #185 regarding the Python integration.
> [Bug] Fix Python node configuration and remove slog

- .github/workflows/ci.yaml
- .github/workflows/docs.yaml
Fixes the CI rust toolchain version and uses [rust-cache](https://github.com/Swatinem/rust-cache) to cache dependencies and speed up CI runs.
> Speed up CI

- python/erdos/message.py
Adds the `Message._serialize_data()` method which serializes the message's data field using `pickle`. When the message is sent, the data field does not need to be serialized again which reduces the cost of sending the message.
Also updates some documentation.
> [Python] Support serializing message data before sending

- README.md
- erdos/src/lib.rs
- python/doc/source/intro.rst
- Cleans up the README.
- Add reference to D3 paper.
> Update readme and documentation
